#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The sp410-cups-driver contributors.
"""
Generate the PPD files for sp410-cups-driver.

The PPDs are generated (rather than hand-edited) so that every model shares
one option table and stays in sync with what src/settings.c parses.

    python3 ppd/gen_ppd.py            # writes ppd/*.ppd
    python3 ppd/gen_ppd.py --check    # exit 1 if committed PPDs are stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
VERSION = (ROOT / "VERSION").read_text().strip()

FILTER = "sp410-rastertotspl"
PT_PER_MM = 72.0 / 25.4

# (model key, ModelName, 1284 MDL, tested?)  -- see docs/HARDWARE.md
MODELS = [
    ("sp410",   "SP410",   "SP410",   False),
    ("sp410bt", "SP410BT", "SP410BT", False),
    ("sp420",   "SP420",   "SP420",   False),
]

# (keyword, label, width_pt, height_pt)
INCH_SIZES = [
    (4, 6), (4, 4), (4, 3), (4, 2), (4, 1),
    (3, 2), (3, 1), (2, 1), (2.25, 1.25), (2.25, 0.75),
]
MM_SIZES = [
    (100, 150), (100, 100), (100, 70), (100, 50), (80, 50),
    (70, 40), (60, 40), (57, 32), (50, 30), (40, 30), (38, 25),
]

MAX_W_MM, MAX_H_MM = 108, 300
MIN_W_MM, MIN_H_MM = 20, 10


def fmt(v: float) -> str:
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return s


def page_sizes():
    out = []
    for w, h in INCH_SIZES:
        wp, hp = w * 72, h * 72
        key = f"w{round(wp)}h{round(hp)}"
        out.append((key, f'{fmt(w)} x {fmt(h)} in', wp, hp))
    for w, h in MM_SIZES:
        wp, hp = w * PT_PER_MM, h * PT_PER_MM
        out.append((f"{w}x{h}mm", f"{w} x {h} mm", wp, hp))
    return out


def pick_one(key, label, order, default, choices, group_comment=None):
    """choices: list of (choice_keyword, choice_label, invocation)."""
    lines = []
    if group_comment:
        lines.append(f"*% {group_comment}")
    lines.append(f"*OpenUI *{key}/{label}: PickOne")
    lines.append(f"*OrderDependency: {order} AnySetup *{key}")
    lines.append(f"*Default{key}: {default}")
    for kw, lab, inv in choices:
        lines.append(f'*{key} {kw}/{lab}: "{inv}"')
    lines.append(f"*CloseUI: *{key}")
    return lines


def mm_choices(values, default_label_suffix=" mm"):
    out = []
    for v in values:
        out.append((str(v), f"{v}{default_label_suffix}", ""))
    return out


def build(model_key, model, mdl, tested) -> str:
    L = []
    a = L.append
    a('*PPD-Adobe: "4.3"')
    a("*%")
    a(f"*% iDPRT {model} - sp410-cups-driver {VERSION}")
    a("*% Generated by ppd/gen_ppd.py - do not edit by hand.")
    a("*% SPDX-License-Identifier: Apache-2.0")
    a("*% Independent open-source driver; not affiliated with or endorsed by iDPRT.")
    if not tested:
        a("*% Hardware status: protocol-compatible, awaiting hardware confirmation.")
    a("*%")
    a('*FormatVersion: "4.3"')
    a(f'*FileVersion: "{VERSION}"')
    a("*LanguageVersion: English")
    a("*LanguageEncoding: ISOLatin1")
    a(f'*PCFileName: "{model_key.upper()[:8]}.PPD"')
    a('*Manufacturer: "iDPRT"')
    a(f'*Product: "({model})"')
    a(f'*ModelName: "iDPRT {model}"')
    a(f'*ShortNickName: "iDPRT {model} (open)"')
    a(f'*NickName: "iDPRT {model}, sp410-cups-driver {VERSION}"')
    a(f'*1284DeviceID: "MFG:iDPRT;MDL:{mdl};CMD:TSPL;"')
    a('*PSVersion: "(3010.000) 0"')
    a('*LanguageLevel: "3"')
    a("*ColorDevice: False")
    a("*DefaultColorSpace: Gray")
    a("*FileSystem: False")
    a('*Throughput: "6"')
    a("*LandscapeOrientation: Plus90")
    a("*TTRasterizer: Type42")
    a("*cupsVersion: 2.2")
    a("*cupsModelNumber: 410")
    a("*cupsManualCopies: True")
    a(f'*cupsFilter: "application/vnd.cups-raster 50 {FILTER}"')
    a('*cupsLanguages: "en"')
    a("")

    sizes = page_sizes()
    default = "w288h432"

    a("*OpenUI *PageSize/Media Size: PickOne")
    a("*OrderDependency: 10 AnySetup *PageSize")
    a(f"*DefaultPageSize: {default}")
    for k, lab, w, h in sizes:
        a(f'*PageSize {k}/{lab}: "<</PageSize[{fmt(w)} {fmt(h)}]/ImagingBBox null>>setpagedevice"')
    a("*CloseUI: *PageSize")
    a("")
    a("*OpenUI *PageRegion/Media Size: PickOne")
    a("*OrderDependency: 10 AnySetup *PageRegion")
    a(f"*DefaultPageRegion: {default}")
    for k, lab, w, h in sizes:
        a(f'*PageRegion {k}/{lab}: "<</PageSize[{fmt(w)} {fmt(h)}]/ImagingBBox null>>setpagedevice"')
    a("*CloseUI: *PageRegion")
    a("")
    a(f"*DefaultImageableArea: {default}")
    for k, lab, w, h in sizes:
        a(f'*ImageableArea {k}/{lab}: "0 0 {fmt(w)} {fmt(h)}"')
    a(f"*DefaultPaperDimension: {default}")
    for k, lab, w, h in sizes:
        a(f'*PaperDimension {k}/{lab}: "{fmt(w)} {fmt(h)}"')
    a("")
    a(f'*MaxMediaWidth: "{fmt(MAX_W_MM * PT_PER_MM)}"')
    a(f'*MaxMediaHeight: "{fmt(MAX_H_MM * PT_PER_MM)}"')
    a("*HWMargins: 0 0 0 0")
    a('*CustomPageSize True: "pop pop pop <</PageSize[5 -2 roll]/ImagingBBox null>>setpagedevice"')
    a(f"*ParamCustomPageSize Width: 1 points {fmt(MIN_W_MM * PT_PER_MM)} {fmt(MAX_W_MM * PT_PER_MM)}")
    a(f"*ParamCustomPageSize Height: 2 points {fmt(MIN_H_MM * PT_PER_MM)} {fmt(MAX_H_MM * PT_PER_MM)}")
    a("*ParamCustomPageSize WidthOffset: 3 points 0 0")
    a("*ParamCustomPageSize HeightOffset: 4 points 0 0")
    a("*ParamCustomPageSize Orientation: 5 int 0 0")
    a("")

    L += pick_one("Resolution", "Resolution", 20, "203dpi", [
        ("203dpi", "203 dpi",
         "<</HWResolution[203 203]/cupsRowCount 0/cupsRowFeed 0/cupsRowStep 0>>setpagedevice"),
    ])
    a("")
    L += pick_one("ColorModel", "Rendering", 20, "Gray", [
        ("Gray", "Grayscale (driver halftoning)",
         "<</cupsColorOrder 0/cupsColorSpace 0/cupsBitsPerColor 8>>setpagedevice"),
        ("BW", "Black and White (renderer halftoning)",
         "<</cupsColorOrder 0/cupsColorSpace 3/cupsBitsPerColor 1>>setpagedevice"),
    ])
    a("")

    a("*OpenGroup: Printer/Printer Settings")
    L += pick_one("Darkness", "Darkness", 30, "Default",
                  [("Default", "Printer Default", "")] +
                  [(str(i), f"{i}" + (" (lightest)" if i == 0 else " (darkest)" if i == 15 else ""), "")
                   for i in range(16)])
    L += pick_one("PrintSpeed", "Print Speed", 30, "Default",
                  [("Default", "Printer Default", "")] +
                  [(str(i), f"{i} in/s ({round(i * 25.4)} mm/s)", "") for i in range(2, 7)])
    L += pick_one("PrintDirection", "Print Direction", 30, "Normal", [
        ("Normal", "Normal", ""),
        ("Rotate180", "Rotated 180 degrees", ""),
    ])
    a("*CloseGroup: Printer")
    a("")

    a("*OpenGroup: Media/Media Handling")
    L += pick_one("MediaTracking", "Media Tracking", 30, "Gap", [
        ("Gap", "Labels with gaps (die-cut)", ""),
        ("BlackMark", "Black mark", ""),
        ("Continuous", "Continuous roll", ""),
    ])
    L += pick_one("GapHeight", "Gap / Mark Height", 30, "3",
                  mm_choices([0, 1, 2, 3, 4, 5, 6, 8, 10]))
    L += pick_one("GapOffset", "Gap / Mark Offset", 30, "0",
                  mm_choices([0, 1, 2, 3, 5]))
    L += pick_one("TearOff", "Advance to Tear Bar", 30, "True", [
        ("True", "Yes", ""),
        ("False", "No", ""),
    ])
    L += pick_one("TearOffset", "Tear Position Adjust", 30, "0",
                  mm_choices([-3, -2, -1, 0, 1, 2, 3]))
    a("*CloseGroup: Media")
    a("")

    a("*OpenGroup: Image/Image Quality")
    L += pick_one("Dither", "Halftoning", 30, "Auto", [
        ("Auto", "Automatic (crisp text, dithered photos)", ""),
        ("Threshold", "Threshold (barcodes / text)", ""),
        ("Atkinson", "Atkinson dither (photos)", ""),
        ("FloydSteinberg", "Floyd-Steinberg dither", ""),
        ("Ordered", "Ordered 8x8 Bayer", ""),
    ])
    L += pick_one("Threshold", "Black Threshold", 30, "128", [
        ("64", "Darker (64)", ""),
        ("96", "Slightly darker (96)", ""),
        ("128", "Normal (128)", ""),
        ("160", "Slightly lighter (160)", ""),
        ("192", "Lighter (192)", ""),
    ])
    L += pick_one("ShiftX", "Horizontal Shift", 30, "0",
                  mm_choices([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]))
    L += pick_one("ShiftY", "Vertical Shift", 30, "0",
                  mm_choices([-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]))
    a("*CloseGroup: Image")
    a("")
    a("*% End of PPD")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify the committed PPDs match the generator")
    ap.add_argument("--outdir", type=pathlib.Path, default=HERE)
    args = ap.parse_args()

    stale = []
    for key, model, mdl, tested in MODELS:
        text = build(key, model, mdl, tested)
        path = args.outdir / f"idprt-{key}.ppd"
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(path.name)
        else:
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
    if stale:
        print("stale PPDs (run `make ppd`): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
